version: "3.9"  # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb+srv://username:password@localhost/mealtally_ver2
