FROM node:14.5.0-alpine

WORKDIR /srv

# RUN apt-get update \
#     && apt-get install git -y

RUN apk --no-cache --virtual build-dependencies add \
    python \
    git \
    make \
    g++
# ENV PYTHON /usr/bin/python3
RUN npm install -g nodemon

COPY package.json ./

# RUN npm install --legacy-peer-deps
RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080
CMD ["npm", "start"]
